export const ADD_USER_INFO = 'ADD_USER_INFO';
export const ADD_AWS_ACCOUNT = 'ADD_AWS_ACCOUNT';
export const ADD_LOGIN_INFO = 'ADD_LOGIN_INFO';
export const ADD_CREDENTIALS = 'ADD_CREDENTIALS';


//###############################################
//AWS Reducer All Functions
//###############################################

export const ADD_LAMBDA = 'ADD_LAMBDA';
export const ADD_FUNCTION_LOGS = 'ADD_FUNCTION_LOGS';
export const REMOVE_FUNCTION_LOGS = 'REMOVE_FUNCTION_LOGS';
export const ADD_INVOCATIONS_ALLDATA = 'ADD_INVOCATIONS_ALLDATA';
export const ADD_ERRORS_ALLDATA = 'ADD_ERRORS_ALLDATA';
export const ADD_THROTTLES_ALLDATA = 'ADD_THROTTLES_ALLDATA';
export const UPDATE_RENDER = 'UPDATE_RENDER';
export const UPDATE_FETCH_TIME = 'UPDATE_FETCH_TIME';
export const UPDATE_FUNCTION_LOGS = 'UPDATE_FUNCTION_LOGS';

//###############################################
//AWS Reducer By Function
//###############################################

export const UPDATE_FETCH_TIME_BYFUNC = 'UPDATE_FETCH_TIME_BYFUNC';
export const UPDATE_RENDER_BYFUNC = 'UPDATE_RENDER_BYFUNC';
export const ADD_INVOCATIONS_BYFUNCDATA = 'ADD_INVOCATIONS_BYFUNCDATA';
export const ADD_ERRORS_BYFUNCDATA = 'ADD_ERRORS_BYFUNCDATA';
export const ADD_THROTTLES_BYFUNCDATA = 'ADD_THROTTLES_BYFUNCDATA';
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';
export const ADD_API_GATEWAYS = 'ADD_API_GATEWAYS';
export const ADD_API_METRIC_CHARTS = 'ADD_API_METRIC_CHARTS';
export const REMOVE_API_METRIC_CHARTS = 'REMOVE_API_METRIC_CHARTS';
export const UPDATE_API_METRIC_CHARTS = 'UPDATE_API_METRIC_CHARTS';
export const ADD_REGION = 'ADD_REGION';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_USER_DETAILS_AFTER_PROFILE_UPDATE =
  'UPDATE_USER_DETAILS_AFTER_PROFILE_UPDATE';
